### PR TITLE
Refactory server

### PR DESCRIPTION
**Pull request by tekig**
The server has been rewritten.
The biggest improvement was the automatic generation of markers.

### CODE REVIEW

**Comment by Fank** [comment]
Current:
image

New:
image

**Comment by Fank** [comment]
Flags are black
image

**Comment by tekig** [comment]
> Flags are black
> image

Default color, sends that the color is located in the config of this marker. I think it will work
```sqf
params ["_color", "_type"];
if (_color == "Default") then {
  _color = (configfile >> "CfgMarkers" >> _type >> "color") call BIS_fnc_colorConfigToRGBA call bis_fnc_colorRGBtoHTML;
} else {
  _color = getarray (configfile >> "CfgMarkerColors" >> _color >> "color") call bis_fnc_colorRGBtoHTML;
}
```

**Comment by Fank** [comment]
> > Flags are black
> > image
> 
> Default color, sends that the color is located in the config of this marker. I think it will work
> 
> ```sqf
> params ["_color", "_type"];
> if (_color == "Default") then {
>   _color = (configfile >> "CfgMarkers" >> _type >> "color") call BIS_fnc_colorConfigToRGBA call bis_fnc_colorRGBtoHTML;
> } else {
>   _color = getarray (configfile >> "CfgMarkerColors" >> _color >> "color") call bis_fnc_colorRGBtoHTML;
> }
> ```

This is current
image
And old records should still work

**Comment by Fank** [comment]
Current:
image

New
image

**Comment by Fank** [comment]
CUP magazine icons are missing
Current:
image


New:
image

**Comment by Fank** [comment]
A3 magazine icons are missing:
Current:
image

New:
image

**Comment by tekig** [comment]
> And old records should still work

In my opinion, drawing Arma 3 markers is more important, if the color was misspelled, it doesn't need to be corrected that way. You agree with me?

**Comment by tekig** [comment]
> Current:
> image
> 
> New
> image

Can you send a recording?

**Comment by Fank** [comment]
> > And old records should still work
> 
> In my opinion, drawing Arma 3 markers is more important, if the color was misspelled, it doesn't need to be corrected that way. You agree with me?

I do agree that the marker information should be collected correctly, but can we fix old records?

**Comment by tekig** [comment]
> I do agree that the marker information should be collected correctly, but can we fix old records?

No, this is a write error. It is written as #000000 (black), so it appears as black. In the old version, the bug is that if you draw a black gas station in Arma 3, then the gas station will be white in the OCAP.

**Pull request merged**
