### PR TITLE
Dont draw marker if not visible

### LINKED ISSUE #22: Markers flashing sometimes
It looks like marker will appear and check in the next frame if it should be shown or not, and then hide it if not.

This causes that markers are shortly visible and then disappears, which can be quite confusing.

### PR DESCRIPTION
**Pull request by Fank**
https://github.com/OCAP2/OCAP/issues/14

### CODE REVIEW

**Comment by indig0fox** [comment]
Add conditions to show() in addition to manageFrame() to make sure that it's not having opacity set if the UI side isn't selected. otherwise you're likely to have manageFrame hide it, then updateAtFrame show it again without that condition
https://github.com/OCAP2/web/blob/340a219c0a172c6ee6a8882f2c99f3886eace3de/static/scripts/ocap.marker.js#L427-L440

**Comment by Fank** [comment]
I don't think changes are needed here, because `show()` is called everytime by `_updateAtFrame()` as long as its visible.

**Comment by indig0fox** [comment]
It's mainly to avoid a call to hide() at manageFrame for every non-active marker, followed by a show() at updateFrame, then another hide in the next frame if marker still present but ui.side not matching.

**Comment by Fank** [comment]
I don't get it, can you do the changes you are surgessting on this branch?

**Review by indig0fox — APPROVED** [review]

**Pull request merged**
